channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - conda
  - pip:
      - azure-identity==1.8
      - azureml-sdk==1.51.0
      - azure-storage-blob==12.15.0
      - protobuf~=3.20
      - numpy==1.20.3
      - tensorflow-gpu==2.2.0
      - keras<=2.3.1
      - joblib==1.2.0
      - fusepy==3.0.1
      - scikit-learn==1.2.2
      - scipy==1.4.1
      - applicationinsights==0.11.10
      - pandas==2.0.0
      - azureml-defaults==1.51.0
      - azureml-core==1.51.0
      - azureml-inference-server-http==0.8.4
      - azure-storage-file-datalake==12.10.0
      - azure-keyvault==4.2.0
      - openpyxl==3.1.2
      - lime
name: model-env-endpoints